spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_market_online
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
